# Generated by Django 4.2.6 on 2024-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_foundperson_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpersonlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='foundpersonlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='missingpersonlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='missingpersonlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
    ]
