# Generated by Django 4.2.6 on 2024-03-29 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_foundpersonlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpersonlocation',
            name='time_found',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='missingpersonlocation',
            name='time_seen',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
