# Generated by Django 4.2.6 on 2024-03-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_foundpersonlocation_time_found_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpersonlocation',
            name='found_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.foundperson'),
        ),
    ]
