# Generated by Django 4.2.6 on 2024-03-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_foundpersonlocation_found_person'),
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='found_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.foundperson'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found')], default='missing', max_length=20),
        ),
    ]
