# Generated by Django 4.2.6 on 2024-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0002_case_found_person_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found')], default='missing', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
