# Generated by Django 4.2.6 on 2024-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0003_case_type_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found')], max_length=20),
        ),
    ]
