# Generated by Django 4.2.6 on 2024-03-30 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Statistics', '0006_remove_case_notes_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remarks',
            new_name='Remark',
        ),
    ]
